name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  config-file-glob:
    description: 'Matcher to locate Vizzly config files'
    required: true
    default: 'vizzly.config.json'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config-file-glob }}