name: 'Validate Vizzly config'
description: 'Validate Vizzly configs as part of your CI/CD process for Vizzly dashboards.'
inputs:
  config-file-glob:
    description: 'Matcher to validate one or more Vizzly config files'
    required: true
    default: 'vizzly.config.json'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--config "${{ inputs.config-file-glob }}"'
